SELECT C.*
FROM TBL_BOARD B
INNER JOIN TBL_COMMENT C ON B.BOARDNO = C.BOARDNO
WHERE B.BOARDNO = 1;

-- 1번 게시글에 대한 댓글 수
SELECT COUNT(*) AS CNT
FROM TBL_BOARD B
INNER JOIN TBL_COMMENT C ON B.BOARDNO = C.BOARDNO
WHERE B.BOARDNO = 1
GROUP BY B.BOARDNO;

-- 각 게시글에 대한 댓글 수
SELECT COUNT(*) AS CNT, B.BOARDNO
FROM TBL_BOARD B
INNER JOIN TBL_COMMENT C ON B.BOARDNO = C.BOARDNO
GROUP BY B.BOARDNO;

-- 게시글 번호, 제목, 내용, 댓글 개수를 출력하세요.
SELECT B.BOARDNO, B.TITLE, B.CONTENTS, COUNT(*) AS COMMENT_CNT
FROM TBL_BOARD B
INNER JOIN TBL_COMMENT C ON B.BOARDNO = C.BOARDNO
GROUP BY B.BOARDNO, B.TITLE, B.CONTENTS;

SELECT B.BOARDNO, TITLE, CONTENTS, COMMENT_CNT
FROM TBL_BOARD B
INNER JOIN (
    SELECT B.BOARDNO, COUNT(*) AS COMMENT_CNT
    FROM TBL_BOARD B
    INNER JOIN TBL_COMMENT C ON B.BOARDNO = C.BOARDNO
    GROUP BY B.BOARDNO
) C ON B.BOARDNO = C.BOARDNO;

SELECT B.BOARDNO, TITLE, CONTENTS, NVL(CNT, 0)
FROM TBL_BOARD B
LEFT JOIN (
    SELECT BOARDNO, COUNT(*) AS CNT
    FROM TBL_COMMENT
    GROUP BY BOARDNO
) C ON B.BOARDNO = C.BOARDNO
ORDER BY BOARDNO;








SELECT * FROM TBL_BOARD;
SELECT * FROM TBL_COMMENT;
SELECT * FROM TBL_BOARDFILE;







-- STU 테이블에서 학번, 이름, 학년, 자신보다 높은 학년의 사람 수
SELECT S1.STUNO, S1.NAME, S1.GRADE, CNT
FROM STU S1
INNER JOIN (
    SELECT S1.STUNO, COUNT(S2.GRADE) AS CNT
    FROM STU S1
    LEFT JOIN STU S2 ON S1.GRADE < S2.GRADE
    GROUP BY S1.STUNO
) S2 ON S1.STUNO = S2.STUNO;

SELECT S1.STUNO, S1.NAME, S1.GRADE, COUNT(S2.GRADE) AS "높은 학년" 
FROM STU S1
LEFT JOIN STU S2 ON S1.GRADE < S2.GRADE
GROUP BY S1.STUNO, S1.NAME, S1.GRADE;

SELECT COUNT(GRADE)
FROM STU
GROUP BY GRADE;


-- STUDENT, ENROL, SUBJECT

-- 1. 학생이름, 학과, 과목명, 점수 출력
SELECT STU_NAME, STU_DEPT, SUB_NAME, ENR_GRADE
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
INNER JOIN SUBJECT SUB ON E.SUB_NO = SUB.SUB_NO;

-- 2. 시험을 안본 학생들은 점수를 0점으로 출력
SELECT STU_NAME, STU_DEPT, NVL(SUB_NAME, '안봄') AS SUB_NAME, NVL(ENR_GRADE, 0) AS ENR_GRADE
FROM STUDENT S
LEFT JOIN ENROL E ON S.STU_NO = E.STU_NO
LEFT JOIN SUBJECT SUB ON E.SUB_NO = SUB.SUB_NO;


SELECT * FROM STUDENT;
SELECT * FROM ENROL;
SELECT * FROM SUBJECT;
