-- 서브 쿼리

SELECT *
FROM T_EMP
WHERE PAY = (SELECT MAX(PAY) FROM T_EMP);

SELECT *
FROM T_EMP
WHERE DEPTNO IN (1001, 1005); -- IN -> OR라 생각하면 된다.

SELECT *
FROM STUDENT
WHERE STU_HEIGHT > (SELECT AVG(STU_HEIGHT) FROM STUDENT) AND STU_GRADE = 1;

SELECT *
FROM STUDENT
WHERE STU_WEIGHT > (SELECT AVG(STU_WEIGHT) FROM STUDENT);

SELECT AVG(STU_WEIGHT)
FROM STUDENT;

SELECT *
FROM STUDENT;