-- 숫자를 넣으면 2배로 리턴해주는 함수
CREATE OR REPLACE FUNCTION MULTI(P_VALUE NUMBER)
RETURN NUMBER
IS
BEGIN
    RETURN P_VALUE * 2;
END;
/
-- 함수는 리턴이 있어야하며, 리턴 타입도 지정해주어야한다.

-- 2024-07-17 09:38:30
SELECT TO_CHAR(HIREDATE, 'YYYY-MM-DD HH24:MI:SS') HIREDATE
FROM EMP;

SELECT FORMAT_DATE(HIRDATE) AS HIREDATE
FROM EMP;


CREATE OR REPLACE FUNCTION FORMAT_DATE(P_DATE DATE)
RETURN VARCHAR2
IS
BEGIN
    RETURN TO_CHAR(P_DATE, 'YYYY-MM-DD HH24:MI:SS');
END;
/

SELECT FORMAT_DATE(HIREDATE) AS HIREDATE
FROM EMP;

    
    
    