SELECT 
    ENAME, JOB
FROM EMP
WHERE SAL >= 1500
UNION
SELECT 
    ENAME, JOB
FROM EMP
WHERE COMM IS NOT NULL;

SELECT 
    ENAME, JOB, SAL+NVL(COMM,0) AS SAL_COMM
FROM EMP
WHERE SAL >= 1500
UNION ALL
SELECT 
    ENAME, JOB, SAL+NVL(COMM,0)
FROM EMP
WHERE COMM IS NOT NULL;
-- 컬럼명은 위에서 정해져서 내려온다.

SELECT 이름, 평균점수
FROM (
    SELECT 
        STU_NAME 이름,
        AVG(ENR_GRADE) AS 평균점수,
        1 AS ORDERKEY
    FROM STUDENT S
    INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
    GROUP BY S.STU_NO, STU_NAME
    UNION
    SELECT 
        '전체평균',
        ROUND(AVG(ENR_GRADE), 1),
        2 AS ORDERKEY
    FROM ENROL
    ORDER BY ORDERKEY, 평균점수 DESC
);


